# Generated by Django 6.0.4 on 2026-04-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='description',
            field=models.TextField(default='', verbose_name='Опис'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна'),
        ),
    ]
